name: user_panel
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  dropdownfield: ^1.0.3
  google_maps_flutter:
  connectivity:
  country_code_picker:
  firebase_core:
  firebase_auth: ^0.20.0+1
  cloud_firestore:
  firebase_storage:
#  firebase_database: ^6.0.0
  provider:
  shared_preferences:
  intl:
  image_picker: ^0.6.7+22
  cached_network_image: ^2.5.1
  country_state_city_picker:
  alphabet_list_scroll_view: ^1.0.6
  url_launcher:
  esys_flutter_share:
#  share: ^0.6.5+4
#  http: ^0.12.2
  pie_chart:
  aamarpay: ^0.0.7
  flutter_staggered_animations:
  expandable_text:
  permission_handler:
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/banner.png
    - assets/banner2.png
    - assets/male.png
    - assets/female.png
    - assets/patient_apps.jpg
    - assets/doctor_patient.png
    - assets/loadingimage.gif
    - assets/home_icon/notifications.png
    #  - Home
    - assets/home_icon/appointment.png
    - assets/home_icon/blog.png
    - assets/home_icon/forum.png
    - assets/home_icon/medicine.png
    - assets/home_icon/prescription.png
    - assets/home_icon/review.png
    - assets/home_icon/support.png
    - assets/home_icon/doctor.png
#    - assets/home_icon/patient_questions.jpg
    - assets/home_icon/shopping.png
    - assets/home_icon/credit_assesment.png
    - assets/home_icon/health_insurance.png
    - assets/home_icon/join_riders.png
    - assets/home_icon/account.png
    - assets/home_icon/discount.png
    #  - Medical Category
#    - assets/medical_category/coronavirus.png
    - assets/medical_category/cardiology.png
    - assets/medical_category/chest.png
    - assets/medical_category/cancer.png
    - assets/medical_category/dentist.png
    - assets/medical_category/diabetes.png
    - assets/medical_category/eye.png
    - assets/medical_category/gastroenterology.png
    - assets/medical_category/ent.png
    - assets/medical_category/gynecology.png
    - assets/medical_category/hematology.png
    - assets/medical_category/herbal.png
    - assets/medical_category/homeopathic.png
    - assets/medical_category/medicine.png
    - assets/medical_category/pain_medicine.png
    - assets/medical_category/neuro_medicine.png
    - assets/medical_category/neurosurgery.png
    - assets/medical_category/nutrition.png
    - assets/medical_category/oncology.png
    - assets/medical_category/pediatrics.png
    #- assets/medical_category/nephrology.png
    - assets/medical_category/orthopaedic.png
    - assets/medical_category/physical_medicine.png
    - assets/medical_category/physiotherapy.png
    - assets/medical_category/plastic_surgery.png
    - assets/medical_category/skin.png
    - assets/medical_category/thyroid.png
    - assets/medical_category/urology.png
    - assets/medical_category/urology_Specialist.png
    - assets/medical_category/psychiatrist.png
    - assets/medical_category/vascular_surgery.png
    # -  Social icon
    - assets/social_icon/email_48.png
    - assets/social_icon/facebook_48.png
    - assets/social_icon/globe_48.png
    - assets/social_icon/linkedin_48.png
    - assets/social_icon/phone_48.png
    - assets/social_icon/twitter_48.png
    - assets/icons/email-send100.png
    - assets/icons/facebook128.png
    - assets/icons/linkedin128.png
    - assets/icons/marker100.png
    - assets/icons/twitter128.png
    - assets/icons/youtube128.png
    - assets/icons/pinterest128.png
  #  - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
